apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events
  namespace: argo-events

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager
  namespace: argo-events
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: argo-events
subjects:
  - kind: ServiceAccount
    name: argo-events
    namespace: argo-events
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
