apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  replicas: 1
  service:
    metadata:
      labels:
        foo: bar
      annotations:
        foo: bar
    ports:
      - port: 80
        targetPort: 8080
  webhook:
    example:
      endpoint: /example
      method: POST
      port: "8080"
