apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: temporal
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: temporal project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: temporal
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - git:
      repoURL: https://github.com/sdobrovolschi/temporal-deployment.git
      revision: HEAD
      files:
      - path: apps/**/config.json
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: '{{ .app }}'
      name: '{{ .app }}'
      namespace: argocd
    spec:
      project: temporal
      destination:
        name: '{{ .destination.name }}'
        namespace: '{{ .destination.namespace }}'
      sources:
      - repoURL: '{{ .chart.repository }}'
        chart: '{{ .chart.name }}'
        targetRevision: '{{ .chart.version }}'
        helm:
          valueFiles:
            - $values/{{ .path.path }}/replicas.yaml
            - $values/{{ .path.path }}/settings.yaml
            - $values/{{ .path.path }}/version.yaml
      - repoURL: https://github.com/sdobrovolschi/temporal-deployment.git
        targetRevision: HEAD
        ref: values
      ignoreDifferences:
      - kind: Application
        group: argoproj.io
        jsonPointers:
        - /status
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - FailOnSharedResource=true
        - PruneLast=true
