separateWorker:
  enabled: true
  default:
    replicaCount: 1
    resources:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
  workspace:
    replicaCount: 1
    resources:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
  global:
    replicaCount: 1
    resources:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
env:
  - name: DATABASE_HOST
    value: postgresql-cluster-rw.postgresql-system.svc.cluster.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: dittofeed
  - name: DATABASE_USER
    value: postgres
  - name: DATABASE_PASSWORD
    value: 7FahOz5UXIaQ65tbsLxyQg4oIxnBpIfT1ZWc8TRecNKCmAfq7i0hSjsoIEY8PETV
  - name: CLICKHOUSE_HOST
    value: http://chi-clickhouse-main-0-0.clickhouse-operator.svc.cluster.local:8123
  - name: CLICKHOUSE_USER
    value: app
  - name: CLICKHOUSE_PASSWORD
    value: qwerty
  - name: CLICKHOUSE_DATABASE
    value: dittofeed
  - name: TEMPORAL_ADDRESS
    value: release-name-temporal-frontend-headless.temporal.svc.cluster.local:7233
  - name: TEMPORAL_NAMESPACE
    value: dittofeed
  - name: PASSWORD
    value: "1234"
  - name: BOOTSTRAP
    value: "false"
  - name: LOG_LEVEL
    value: info
  - name: COMPUTE_PROPERTIES_INTERVAL
    value: "10000"
  - name: COMPUTE_PROPERTIES_SCHEDULER_INTERVAL
    value: "30000"
  - name: OPEN_ID_CLIENT_ID
    value: dittofeed
  - name: OPEN_ID_CLIENT_SECRET
    value: S3FePXTWteNddayuSNZdaKPlCVE6N7VD
  - name: SECRET_KEY
    value: 5O3pMiEo3fjqh17XT676BUnXxMZ5/K/fvmPoGiDIVu0=
  - name: AUTH_MODE
    value: 'multi-tenant'
  - name: AUTH_PROVIDER
    value: 'keycloak'
  - name: SIGNOUT_URL
    value: '/dashboard/signout'
  - name: OPEN_ID_ISSUER
    value: 'http://localhost:8585/realms/users'
  - name: OPEN_ID_AUTHORIZATION_URL
    value: 'http://localhost:8585/realms/users/protocol/openid-connect/auth'
  - name: OPEN_ID_TOKEN_URL
    value: 'http://localhost:8585/realms/users/protocol/openid-connect/token'
  - name: OPEN_ID_USER_INFO_URL
    value: 'http://localhost:8585/realms/users/protocol/openid-connect/userinfo'
  - name: OPEN_ID_END_SESSION_ENDPOINT
    value: 'http://localhost:8585/realms/users/protocol/openid-connect/logout'
  - name: OPEN_ID_RETURN_TO_QUERY_PARAM
    value: 'post_logout_redirect_uri'
