apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: exchange-job
  namespace: rabbitmq-system
spec:
  name: exchange-job
  type: fanout
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq-cluster

---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: queue-job1
  namespace: rabbitmq-system
spec:
  name: queue-job1
  autoDelete: false
  durable: true
  type: quorum
  rabbitmqClusterReference:
    name: rabbitmq-cluster

---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding-queue-job1
  namespace: rabbitmq-system
spec:
  source: exchange-job
  destination: queue-job1
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbitmq-cluster

---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: queue-job2
  namespace: rabbitmq-system
spec:
  name: queue-job2
  autoDelete: false
  durable: true
  type: quorum
  rabbitmqClusterReference:
    name: rabbitmq-cluster

---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding-queue-job2
  namespace: rabbitmq-system
spec:
  source: exchange-job
  destination: queue-job2
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbitmq-cluster
