apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/component: service
    app.kubernetes.io/version: 1.0.0
spec:
  selector:
    app.kubernetes.io/name: service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
