apiVersion: sinks.knative.dev/v1alpha1
kind: JobSink
metadata:
  name: event-display
  namespace: rabbitmq-system
spec:
  job:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 2
      ttlSecondsAfterFinished: 30
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: bash:5.3.9
              command: [ "cat" ]
              args:
                - "/etc/jobsink-event/event"
