apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: postgresql-system
spec:
  instances: 3
  logLevel: info
  storage:
    size: 1Gi
  enableSuperuserAccess: true
